language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=allegro
    - LISP=ecl

matrix:
  allow-failures:
    - env: LISP=allegro
    - env: LISP=ecl

before_install:
   # 32-bit libraries needed to run Allegro.
   sudo dpkg --add-architecture i386
   sudo apt-get update
   sudo apt-get install libc6:i386
   sudo apt-get install libgtk2.0-0:i386

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l fiveam -l serapeum -l serapeum/tests
       -e '(setf fiveam:*on-error* :debug
                 fiveam:*on-failure* :debug)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(serapeum.tests:run-tests)'
