language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - curl https://common-lisp.net/project/asdf/archives/asdf.lisp > ~/asdf.lisp

script:
  - cl -l fiveam -l serapeum -l serapeum/tests
       -e '(load #p"~/asdf.lisp")'
       -e '(setf fiveam:*on-error* :debug
                 fiveam:*on-failure* :debug)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(serapeum.tests:run-tests)'
